name: West Point - Class of 2016
favicon: null
layout_spectrum: 0.16326041403226554
typography_spectrum: 0.6281130199786276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9185675769113004
  lightness: 0.8788769384846091
  saturation: 0.38215923006646335
  rhythmicContrast: 0.5211852837819606
purpose: []
